#!/usr/bin/env sh
# Android Plugin - Shell Initialization
# Sets up environment when user runs 'devbox shell'
# Config files are generated by init-hook.sh before this is sourced
# NOTE: This file is sourced (not executed) by devbox init_hook,
# so it must be POSIX sh compatible (no bash-isms).

# Debug logging
if [ -n "${ANDROID_DEBUG_SETUP:-}" ]; then
  echo "[SETUP-$$] Entry: PID=$$, PPID=$PPID, Caller=$(ps -p $PPID -o comm= 2>/dev/null || echo unknown)" >&2
  echo "[SETUP-$$] PWD: $(pwd)" >&2
fi

# Ensure we're being sourced
if ! (return 0 2>/dev/null); then
  echo "ERROR: setup.sh must be sourced, not executed directly" >&2
  exit 1
fi

# Skip all Android setup if ANDROID_SKIP_SETUP=1
# Useful for iOS-only contexts in React Native plugin to avoid SDK downloads
if [ "${ANDROID_SKIP_SETUP:-0}" = "1" ]; then
  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Skipping Android setup (ANDROID_SKIP_SETUP=1)" >&2
  return 0
fi

# Prevent double-loading
if [ "${ANDROID_ENV_LOADED:-}" = "1" ] && [ "${ANDROID_ENV_LOADED_PID:-}" = "$$" ]; then
  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Already loaded in this PID, returning" >&2
  return 0
fi

[ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Setting ANDROID_ENV_LOADED=1 for PID $$" >&2
ANDROID_ENV_LOADED=1
ANDROID_ENV_LOADED_PID="$$"
export ANDROID_ENV_LOADED ANDROID_ENV_LOADED_PID

set -e

# ============================================================================
# Source Dependencies
# ============================================================================

# Source core.sh which handles SDK resolution, PATH setup, etc.
# core.sh will automatically source lib.sh as a dependency
if [ -n "${ANDROID_SCRIPTS_DIR:-}" ] && [ -f "${ANDROID_SCRIPTS_DIR}/platform/core.sh" ]; then
  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Sourcing core.sh..." >&2
  . "${ANDROID_SCRIPTS_DIR}/platform/core.sh"
  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] core.sh sourced" >&2

  # ============================================================================
  # Environment Setup
  # ============================================================================

  # Setup SDK and PATH (functions from core.sh)
  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Calling android_setup_sdk_environment..." >&2
  android_setup_sdk_environment
  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] android_setup_sdk_environment done" >&2

  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Calling android_setup_path..." >&2
  android_setup_path
  [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] android_setup_path done" >&2

  # ============================================================================
  # Validation
  # ============================================================================

  # Optional validation (non-blocking)
  if [ -f "${ANDROID_SCRIPTS_DIR}/domain/validate.sh" ]; then
    [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Running validation..." >&2
    . "${ANDROID_SCRIPTS_DIR}/domain/validate.sh"
    android_validate_sdk || true
    [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Validation complete" >&2
  fi

  # ============================================================================
  # Summary Display
  # ============================================================================

  # Optional summary display on init if INIT_ANDROID is set
  if [ -n "${INIT_ANDROID:-}" ] && [ -z "${CI:-}" ] && [ -z "${GITHUB_ACTIONS:-}" ] && [ -z "${ANDROID_SDK_SUMMARY_PRINTED:-}" ]; then
    [ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Showing summary..." >&2
    ANDROID_SDK_SUMMARY_PRINTED=1
    export ANDROID_SDK_SUMMARY_PRINTED
    android_show_summary
  fi
fi

[ -n "${ANDROID_DEBUG_SETUP:-}" ] && echo "[SETUP-$$] Exit" >&2 || true
